### ISSUE TITLE
Order of output in the Hessian

### ISSUE THREAD

**Issue by WolfgangEnzi** [Herculens/herculens#28]
I think I found some inconsistent order in the output  of the Hessian in the Mass profiles. In particular, for the EPL and Shear the output seems to be:

` return f_xx, f_yy, f_xy`

While for the multipole it looked like

`return f_xx, f_xy, f_yy`

It might be fine that the order is different, but I was wondering if that would affect calculated convergence maps, magnifications, etc, so I though it could be worth raising this as an issue!

**Comment by aymgal** [comment]
Thanks @WolfgangEnzi for noticing this, the commit mentioned fixes it!
